chore: update doc and framework to 1.19
dynamic-framework/dynamic-retail-transfer-template pull request #10
Opened 2024-04-16 19:04 UTC by abe-modyo

2024-04-17 02:36 UTC, efbarong commented
Revisar los problemas de eslint

2024-04-17 21:50 UTC, johannrp27 requested changes

2024-04-17 21:50 UTC, johannrp27 commented on src/components/ModalConfirmTransfer.tsx
> +        onClose={() => closePortal()}
Las mismas observaciones que Eduard
```suggestion
        onClose={closePortal}
```

2024-04-19 15:12 UTC, efbarong approved these changes

2024-04-19 16:38 UTC, johannrp27 approved these changes

2024-04-19 16:43 UTC, merged