refactor: remove new contact form
dynamic-framework/dynamic-retail-transfer-template pull request #15
Opened 2024-09-12 15:19 UTC by lnazarit

tarea: https://modyohq.atlassian.net/jira/software/projects/MPD/boards/262?selectedIssue=MPD-343

2024-09-16 22:53 UTC, efbarong commented on src/components/Avatar.tsx
> +  }
```suggestion
  }
  
```

2024-09-16 22:53 UTC, efbarong commented on src/components/Avatar.tsx
> +  return initials;
```suggestion
  return nameParts.map((part) => part.charAt(0)).join('').toUpperCase();
```

2024-09-16 22:53 UTC, efbarong commented on src/styles/base.scss
Cambiar los **`bs-`** por **`#{$prefix}`**

2024-09-26 03:53 UTC, abe-modyo requested changes
por favor re-revisa el PR siguiendo los comentarios de los otros PR @lnazarit :), revisar el archivo avatar.

2024-09-26 23:08 UTC, efbarong commented on package.json
> +    "@dynamic-framework/ui-react": "^1.30.1",
Podrías dejarlo de una vez en la `1.31.0`

2024-10-01 15:05 UTC, johannrp27 submitted a review, later dismissed

2024-10-01 18:02 UTC, johannrp27 approved these changes

2024-10-02 07:54 UTC, abe-modyo approved these changes
par de commets.

LGTM

2024-10-02 07:54 UTC, abe-modyo commented on src/styles/base.scss
>    .accounts {
sigues necesitando este estilo ?

2024-10-02 07:54 UTC, abe-modyo commented on src/components/ContactListItem.tsx
> +      <DButtonIcon
quedó con el mismo problema de accesibilidad de button en button, pero no problemo, porque ya estaba así, tal vez dejar un issue en deuda técnica sería ideal. :)

2024-10-02 12:29 UTC, lnazarit commented on src/styles/base.scss
>    .accounts {
Eliminé los styles de accounts, era ese ?

2024-10-03 13:07 UTC, abe-modyo approved these changes

2024-10-03 13:34 UTC, johannrp27 approved these changes

2024-10-03 20:19 UTC, merged